name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e enviar a imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: src/Dockerfile
          tags: |
            mhbordalo/fake-shop:latest
            mhbordalo/fake-shop:v${{ github.run_number }}

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configurar o kubectl
        # run: aws eks update-kubeconfig --name eks-desafio
        run: aws eks update-kubeconfig --name eka-desafio

      - name: Deploy dos manifestos no kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            mhbordalo/fake-shop:v${{ github.run_number }}